version: '3.8'
services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000" # React's default port
      - "5000:5000" # Express server port if different
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydb
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - mongo
    command: sh -c "npm install && npm run dev"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data: